# Generated by Django 4.1.4 on 2023-02-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_pricecard_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricetable',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
    ]
